version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL="postgresql://postgres:PASSWORD@db:5432/tourist_db"

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: tourist_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: